CC=gcc -Wall -ansi
BIN=bin
INC=include
LIB=lib
OBJ=obj
SRC=src

PHONY=clean

all: runstack runfifo


${OBJ}/stack_array.o: ${INC}/stack.h ${SRC}/stack_array.c
	${CC} -c -o ${OBJ}/stack_array.o ${SRC}/stack_array.c -I${INC} -DSTACK_SIZE=10

${OBJ}/list_impl.o: ${INC}/list.h ${SRC}/list_impl.c
	${CC} -c -o ${OBJ}/list_impl.o ${SRC}/list_impl.c -I${INC}

${OBJ}/stack_list.o: ${INC}/list.h ${INC}/stack.h ${SRC}/stack_list.c
	${CC} -c -o ${OBJ}/stack_list.o ${SRC}/stack_list.c -I${INC}

${OBJ}/fifo_list.o: ${INC}/list.h ${INC}/fifo.h ${SRC}/fifo_list.c
	${CC} -c -o ${OBJ}/fifo_list.o ${SRC}/fifo_list.c -I${INC}

${LIB}/libstack.a:	${OBJ}/stack_list.o ${OBJ}/list_impl.o
	ar cr ${LIB}/libstack.a ${OBJ}/stack_list.o ${OBJ}/list_impl.o
	ranlib ${LIB}/libstack.a

${LIB}/libfifo.a:	${OBJ}/fifo_list.o ${OBJ}/list_impl.o
	ar cr ${LIB}/libfifo.a ${OBJ}/fifo_list.o ${OBJ}/list_impl.o
	ranlib ${LIB}/libfifo.a

${OBJ}/stack_test.o: ${INC}/stack.h ${SRC}/stack_test.c
	${CC} -c -o ${OBJ}/stack_test.o ${SRC}/stack_test.c -I${INC}  -DSTACK_SIZE=10

${OBJ}/fifo_test.o: ${INC}/fifo.h ${SRC}/fifo_test.c
	${CC} -c -o ${OBJ}/fifo_test.o ${SRC}/fifo_test.c -I${INC}  -DSTACK_SIZE=10

${BIN}/stack_test: ${OBJ}/stack_test.o ${LIB}/libstack.a 
	${CC} -o ${BIN}/stack_test ${OBJ}/stack_test.o ${LIB}/libstack.a
	
${BIN}/fifo_test: ${OBJ}/fifo_test.o ${LIB}/libfifo.a
	${CC} -o ${BIN}/fifo_test ${OBJ}/fifo_test.o ${LIB}/libfifo.a

runstack: ${BIN}/stack_test
	echo "Testing Stack"
	${BIN}/stack_test

runfifo: ${BIN}/fifo_test
	echo "--------------------------------"
	echo "Testing Fifo"
	${BIN}/fifo_test

clean:
	rm -f ${OBJ}/* ${BIN}/* ${LIB}/*
